import '@/styles/globals.css'
import type { Metadata } from 'next'
import type { ReactNode } from 'react'
import { ThemeModeScript } from 'flowbite-react'
import localFont from 'next/font/local'
import { ScrollButton } from '@/components'
import { Navigation } from '@/containers'
import { MovieProvider } from '@/providers'
import { twUtils } from '@/utils'

export const metadata: Metadata = {
  title: 'Movie App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: { children: ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <ThemeModeScript />
      </head>
      <body className={twUtils.clsx('antialiased', redditSans.variable)} suppressHydrationWarning>
        <MovieProvider>
          <Navigation />
          <main className='absolute left-1/2 top-16 -z-10 w-full max-w-screen-2xl -translate-x-1/2' {...props} />
          <ScrollButton />
        </MovieProvider>
      </body>
    </html>
  )
}

const redditSans = localFont({
  variable: '--font-reddit',
  display: 'swap',
  fallback: ['sans-serif'],
  src: [
    { path: '../../public/fonts/RedditSans.woff2', style: 'normal' },
    { path: '../../public/fonts/RedditSans-Italic.woff2', style: 'italic' },
  ],
})
